#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

print_coloumns "" "TEST"

hostname=${HOSTNAME:-$(hostname)}

# print_columns "" "${CA}$(figlet "${hostname}")${CN}"
