#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

user=${USER:-$(id -un)}
hostname=${HOSTNAME:-$(hostname)}

motd=$(cat ${BASE_DIR}/motdtext)

print_columns "" "${motd}"
print_columns "Logged as" "${user}@${hostname}"
echo "\n"
